# Generated by Django 3.0.7 on 2020-06-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_system', '0002_auto_20200605_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=15)),
                ('phonenumber', models.CharField(max_length=10)),
                ('dob', models.DateField()),
            ],
        ),
    ]
