# Generated by Django 3.0.7 on 2020-06-05 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_system', '0003_usermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
